# Generated by Django 6.0.6 on 2026-07-15 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'advisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='current_level',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='current_semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='programme',
            field=models.CharField(choices=[('computer_science', 'B.Sc. Computer Science'), ('software_engineering', 'B.Sc. Software Engineering'), ('cyber_security', 'B.Sc. Cyber Security')], default='software_engineering', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.CharField(default='2025/2026', max_length=16),
        ),
    ]
