# Generated by Django 6.0.7 on 2026-08-03 10:15

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[apps.accounts.models.MatricNumberValidator()]),
        ),
    ]
