# Generated by Django 6.0.6 on 2026-08-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=500, upload_to='profile_photos/'),
        ),
    ]
