# Generated by Django 6.0.6 on 2026-07-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0002_recommendation_status_recommendation_student_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisormessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advisormessage',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=16)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='advisories.advisormessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
