# Generated by Django 6.0.6 on 2026-08-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0004_recommendation_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending_review', max_length=16),
        ),
    ]
