# Generated by Django 6.0.6 on 2026-07-04 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('credit_units', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second')])),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400')])),
                ('description', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('major_topics', models.TextField(blank=True)),
                ('recommended_references', models.TextField(blank=True)),
                ('department_classification', models.CharField(default='Computer Science', max_length=128)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('abstract_reasoning', models.PositiveSmallIntegerField(default=0)),
                ('logical_reasoning', models.PositiveSmallIntegerField(default=0)),
                ('theoretical_knowledge', models.PositiveSmallIntegerField(default=0)),
                ('quantitative_calculation', models.PositiveSmallIntegerField(default=0)),
                ('practical_application', models.PositiveSmallIntegerField(default=0)),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=32)),
                ('grade', models.CharField(blank=True, max_length=8)),
                ('credit_points', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('carryover', 'Carryover')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
